### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by sils1297** [irmen/Tale#14]
Hey, that's a cool thing you built here! May I suggest adding continuous integration against supported python versions? Otherwise tests will break sooner or later, promised. It's really easy to do with travis against linux.

**Comment by sils1297** [comment]
then you'll be able to remove

> (maybe it runs on 3.2 and 3.3 as well but that is not tested.)

from your readme as well ;)

**Comment by sils1297** [comment]
If you want windows CI, you can almost copy our config from https://github.com/coala-analyzer/coala/blob/master/.misc/appveyor.yml and if you want builds against mac you can use something like this https://github.com/coala-analyzer/coala/blob/master/.travis.yml and add linux builds there (we're using CircleCI for linux but having linux and mac together on travis is probably easier for you).

**Comment by irmen** [comment]
thanks for the PR
