### ISSUE TITLE
Add Tutorial

### ISSUE THREAD

**Issue by sils** [irmen/Tale#16]
Hey,

I think you'll really want to have a short tutorial on how to create a story wih Tale. I just got started and well it works but a tutorial would be really nice.

We e.g. did http://coala.readthedocs.org/en/latest/Users/Tutorial/ , step for step instructions, introducing concepts one after each other and an important thing would be an example repository that is split off from the main repository to show how you use it without cloning the source or relying on your directory structure.

**Comment by irmen** [comment]
Didn't want to write docs until now because too many changes were still made.
I guess the api is more or less stabilizing now so yeah this is becoming an opportunity now.

**Comment by irmen** [comment]
Two years ago I wrote the API is more or less stabilizing, but Tale has gone through extensive changes recently. 😄 

Still, things seem to be stabilizing once more so I keep this issue open, a small tutorial goes a long way

**Comment by jeremy886** [comment]
I bookmarked Tale a few years ago but never came around to try it.

Recently I took a course for teachers (Object-oriented Programming in Python by Raspberry Pi Foundation on FutureLearn) and followed along to write a text adventure game (https://trinket.io/library/trinkets/d2e2579527). 

I used a tiny part of it in my classes and it was very well received. I'm interested in doing more but it's not a simple task. I found Tale very pleasant and easy to play and set up although I was stuck in the room with Garfield.

I'm very keen to create a story now. Is there any document around I can read? I hope it is easy to create custom commands and rules.

**Comment by irmen** [comment]
Apart from the apidocs on http://tale.readthedocs.io/ there's no documentation yet. You can run the command ``python3 -m tale.author init your-story-directory`` to set up a minimal story directory structure and start file, but after that, you're pretty much directed to the existing story example code or the library source code itself.

**Comment by irmen** [comment]
@jeremy886 have you tried some more recently? Adding commands should be fairly straightforward with the ``@cmd`` decorator, see the example stories. The hardest part of creating custom commands is is reacting to the parsed command's arguments in a natural manner. Tale's parser is simple but should provide enough information in the ``ParseResult`` object.
Custom "rules" can come in various forms, you can start by investigating overriding the various methods of the Item or Location (or even Living) classes.  Interesting methods to look at are the ``handle_verb`` and the various ``notify_`` methods.  Overriding these can make your mud objects/ rooms react to things that are happening.

**Comment by Ianax** [comment]
I'd be happy to add a bit of tutorial or documentation that helps people get started. I could be writing a bit up as I learn the code, which I've been playing with for the past few days.

What format would be most helpful? Ideas I had include:

- Writing up text documentation.

- Adding to the github wiki

- Updating the garfield tutorial code to be more explicit. The API's are straightforward, and making the code more explicit by doing things like defining the variables going into methods and reorganizing a bit might help new people understand how to extend it.

I was also playing around with abstracting out the location/exit/door code away from the actual python code. Now that I've done it I'm not sure it adds much value without bringing in a different tool.

Whatever you think might be helpful.

**Comment by irmen** [comment]
hi @Ianax I think the most lacking is a basic tutorial of writing a  working IF game and one for a MUD game. Just a simple step-by-step guide to set things up, probably explaining how the 'garfield' demo story works and can be recreated by the user. Then a short overview of some core concepts on the side (such as the way stories/rooms/exits/npcs are set up, the role of the classes in the tale.base package)     

I'm not too happy with the way exits are linked but it's better than it was when using the Exit.connect() helper method...

**Comment by Ianax** [comment]
Where do I put it as I write? Is there a part of the github code? Or how about github wiki?

**Comment by irmen** [comment]
@Ianax good question, I think you could add page(s) to the documentation in https://github.com/irmen/Tale/tree/master/docs/source  and make a pull request.
I'm not sure if you can do the same for the wiki? Haven't tried that yet!
I slightly prefer having a tutorial page(s) in the documentation but the easy edit-ability of the wiki could be great as well for early versions.

**Comment by Ianax** [comment]
Okay, I've started a wiki page and will throw a few sentences in it now and then, with the hope that it will eventually add up to something. Then we can lift it into the actual documentation.

**Comment by Ianax** [comment]
What's the right way to get in touch with you for questions? Do you check the email on the github site?

**Comment by irmen** [comment]
Direct email is fine, using an issue here on github is fine as well. 

Note that Tale is a project on the backburner though. While I really appreciate contributions, I'm not spending much time on it anymore.

**Comment by irmen** [comment]
closing this because there's something on the wiki now
