### ISSUE TITLE
Make params of StoryConfig optional

### ISSUE THREAD

**Issue by sils1297** [irmen/Tale#17]
You probably want to have None or whatever as default values for StoryConfig, when I don't provide all arguments from your demo it just throws an exception saying I should provide all arguments. Would be rather good to make as much as possible optional so in order to get started one can just provide a title only or so. Similar to distutils/setuptools.setup

**Comment by irmen** [comment]
Yeah the story config/init code could use some usability love indeed. Might as well do this soon, it's a simple enhancement

**Comment by irmen** [comment]
Fix this at the same time:

those methods of the Story class should be optional. E.g. a goodbye message can be provided by default and be only overridable. Same with welcome and so on, giving the user an easier learning curve into tale.
