### ISSUE TITLE
Raising exceptions in goodbye() prevents user from exiting game

### ISSUE THREAD

**Issue by sils1297** [irmen/Tale#18]
You probably want to catch exceptions from this method. Also a funny thing would be to be able to use the ActionRefused exception here too :) A game that cannot be ended except through killing it's process would be interesting, making the user feel locked in some location (which might be intentional).

**Comment by irmen** [comment]
hmm, I don't really like your proposal; catching exceptions may hide a bug.
For now I rather see the thing crash hard so the bug is obvious.

I guess to make a game that cannot be quitted the way to go is to overrule the 'quit' command itself.

**Comment by sils1297** [comment]
The problem is that if something goes wrong currently (I.e. goodbye was not
defined at all) the user can't exit the game at all.

**Comment by irmen** [comment]
this will be fixed by #17 where there will always be a (base) goodbye method if you don't choose to override it

**Comment by irmen** [comment]
should be fixed by a7b4c4c77fe59cd8d17daec5fdde2cdd95fc98d6
