### ISSUE TITLE
Make goodbye, welcome, init optional

### ISSUE THREAD

**Issue by sils1297** [irmen/Tale#19]
those methods of the Story class should be optional. E.g. a goodbye message can be provided by default and be only overridable. Same with welcome and so on, giving the user an easier learning curve into tale.

Also it is not obvious why you need `init` as well as `init_player`...

**Comment by irmen** [comment]
init is done once, init_player is done for every player (which, in the case of IF mode, is only one too. But for MUD mode there's many players)

I think I agree with the optional methods, this should be improved at the same time as #17 though. So I'll close this as a dupe and add the suggestion there.
