### ISSUE TITLE
RFE: Add health to buildings and entities

### ISSUE THREAD

**Issue by sils** [irmen/Tale#20]
Would be nice to have a health `@property` for all things. (A nice setter can be used to display messages like "You feel a bit better" or so when health changes.)

**Comment by sils1297** [comment]
related to the example/prototype code at https://github.com/irmen/Tale/issues/23 . One probably wants to do "long term effects" as a general concept which can then be specialized to things like Healing, Burning, ... without more than one or two additional lines of code per specialization.

**Comment by irmen** [comment]
A Living already has stats, which contains many things such as the current hp.
I don't see yet why the additional customization should end up in Tales base classes, instead of your own customized class? Or perhaps try monkeypatching things?  (This is python after all)

**Comment by irmen** [comment]
closing because outdated, feel free to open new issue with more up to date and fleshed out idea
