### ISSUE TITLE
Add way to use locations/people in sentences properly

### ISSUE THREAD

**Issue by sils** [irmen/Tale#22]
Would be nice to be able to do some string like `<name> glowing!` which turns to `The kitchen is glowing` for the location `Kitchen`, `You are glowing` if it's the player and so on. This is localization specific of course which makes this a little hard... however it would be nice to be able to build meaningful sentences more generically to be able to create more abstractions.

**Comment by irmen** [comment]
Yeah, the only formatting helper is "{title}" in tell_others, which is very meager indeed.
This is a hard thing to design and implement. What features should the template language have?

Localization is a non-issue as far as I'm concerned because Tale hasn't been designed to support multiple languages at this time.

**Comment by RealJTG** [comment]
Hi. I'm currently looking for a way to implement some basic i18n (probably with gettext), without complex morphology. There are a lot of hardcoded stuff and some problems with lang.py, but I guess it's only a matter of time. What else problems may I run into?

**Comment by irmen** [comment]
I think another large hurdle will be the command definitions; they have a lot of hardcoded English strings and also depend quite a lot on parsing out English words in the user input.  Similarly the driver has a fair bit of hardcoded stuff and expectations.  The stuff in races.py is not really essential so you could probably take that out quite easily.  Soul.py is a whole different story; good luck on translating the 300 emotes...

**Comment by irmen** [comment]
closing because outdated, feel free to open new issue if so inclined but with more fleshed out ideas about this
