### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by random-access** [irmen/Tale#29]
It would be really nice if Tale could be translated into different languages. The python gettext library (https://docs.python.org/3/library/gettext.html) could be used for that purpose.

**Comment by irmen** [comment]
This is hard. It's not only the printable strings that have to be translated, there's a also parsing logic hard-coded to english sentence structures

See also #22

**Comment by irmen** [comment]
I do agree that it would be nice to have, but I'm not doing it myself.
