### ISSUE TITLE
Incorrect behavior when picking up identical objects

### ISSUE THREAD

**Issue by itsbirdseed** [irmen/Tale#34]
Trying to "take" an item while an identical item is in your inventory will give the response "You’ve already got it." instead of picking up the item.

Steps to reproduce:

- Start garfield demo in wizmode
- Clone the elastic band into your inventory
- Try "take band"

**Comment by irmen** [comment]
What was your expected outcome?

(essentially, the response is correct as it is, no?)

**Comment by itsbirdseed** [comment]
Ah, sorry for the ambiguity, I had a bit of trouble with the wording of the title. The action is technically valid, but it seems like if there are two identical objects, one on the ground and one in your inventory, the parser tries to "take" the inventory item rather than what you'd contextually assume, picking up the item on the ground. Because of this, you can't pick up the item at all unless you move the inventory item to another location or hoover up everything in the location with "take all".

**Comment by irmen** [comment]
"hoover up" :-)

I'll have a look at the priority issue. Seems right that you want to 'take' stuff looking in your environment first (does it even make sense to look in the inventory at all? odd)

Still: even if the parser finds the item in the environment, what do you expect to happen? Have two identical objects in your possession?   I think this will cause other problems to address them properly .   THe parser has no concept of ordinality  if I remember correctly

**Comment by itsbirdseed** [comment]
Thanks for looking! I was assuming there was some functionality for it since the on-ground description had support for multiple items. I was planning on trying something RPG-like where having multiple similar items (ex. healing potions) would be fairly common, but I understand that's not exactly what the framework is built around.

**Comment by irmen** [comment]
It will be a nice addition though to support things like "take first potion" when you carry multiple...

**Comment by irmen** [comment]
@itsbirdseed can you check to see if the change works for you? It should be possible to have multiple items in your inventory now.

**Comment by itsbirdseed** [comment]
Yep, seems to work just fine now, thanks!
