### ISSUE TITLE
zed_is_me crossing: EXCEPTION HERE: LocationIntegrityError: exit not bound

### ISSUE THREAD

**Issue by Ianax** [irmen/Tale#35]
When running the zed_is_me program, attempting to enter the crossing from either the east or the west results in a "EXCEPTION HERE: LocationIntegrityError: exit not bound" error. I believe this is due to a problem with the .add_exits() API for the following reason:

1) The only thing unique about these two exits (I could find) is that they both used the .add_exits() API.

2) Replacing the .add_exits() commands in the magnolia_st.py file and then adding an Exit.connect allowed me to fix the problem when coming from the east. I couldn't fix it from the west, but I think this is my own lack of knowledge.

**Comment by Ianax** [comment]
Same thing happens in the "demo" story. For exits that employ the "Exit.connect" functionality, everything works fine. But the shop uses the "location.add_exit" method and it fails on me when I try to walk to it. The exit is listed though, so I think it just isn't getting bound?

**Comment by irmen** [comment]
thanks I'll look into this
