### ISSUE TITLE
Combat API?

### ISSUE THREAD

**Issue by bubthegreat** [irmen/Tale#36]
Was looking to write a MUD in python and made some headway, but I'm reinventing the wheel it seems - I'm looking to implement something like DIKU/Circle MUD - but I didn't see the ability for combat on here - was there an API that I don't see for combat?

**Comment by irmen** [comment]
There's no combat API, no.
There is one little hook method Living.start_attack()  but it doesn't really do anything useful yet.

On the positive side, this does mean it's possible to add any combat system to Tale that you like, but it does require a lot of work.
Also see ideas/combatmodel.txt
